name: Release

on:
    push:
        tags:
            - 'v*'

jobs:
    release:
        runs-on: ubuntu-latest
        permissions:
            contents: write # Allow actions to push to the repository
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Setup Bun
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: 'latest'

            - name: Install dependencies
              run: bun install

            - name: Build
              run: bun run build

            - name: Install husky
              run: bun install husky --no-save

            - name: Setup npm auth
              run: |
                  echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc

            - name: Publish to NPM
              run: bun publish --no-git-checks
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
